CREATE DATABASE CadCliente

GO
USE CadCliente
GO
CREATE TABLE CLIENTE(
	IDCLIENTE int IDENTITY(1,1) NOT NULL,
	NOMECLIENTE varchar](40) NOT NULL,
	CPF varchar(14) NOT NULL,
	EMAIL varchar(40) NOT NULL,
	TELEFONEFIXO  varchar (11) NOT NULL,
	TELEFONECELULAR varchar (12) NOT NULL,
	TELEFONECOMERCIAL varchar (11) NULL,
	ATIVO bit NOT NULL
) 